server:
  port: 8092

spring:
  zipkin:
    base-url: http://127.0.0.1:9411/
  application:
    name: CLAIMS-MANAGEMENT-SERVICE

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health
  health:
    circuitbreaker:
      enabled: true

resilience4j:
  circuitbreaker:
    instance:
      claimsManagementService:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        automaticTransactionFromOpenToHalfOpenEnabled: true
        failureThreadThreshold: 50
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 5
        sidingWindowSize: 10
        waitDurationInOpenState: 5s
        slidingWindowType: COUNT_BASED

resilience4j.retry:
  instances:
    claimsManagementService:
      maxRetryAttempts: 5
      waitDuration: 10000

resilience4j.ratelimiter:
  instances:
    claimsManagementService:
      limitForPeriod: 10
      limitRefreshPeriod: 1s
      timeoutDuration: 0
      registerHealthIndicator: true
      eventConsumerBufferSize: 100